# Change these first
owner: boumboo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Backu.fr
    url: https://backu.fr
  - name: Backu.net
    url: https://backu.net
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime perso 
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
- name: Actions Ntfy
  run: |
    curl \
      -u :tk_e7m25ztq5x2zmnm87y0m2fgwc5y65 \
      -H "Title: Title here" \
      -H "Content-Type: text/plain" \
      -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ job.status}}' \
      ntfy.backu.fr/95h3E01oEdQeZzGe
